export enum HttpStatusCodes {
    SUCCESS_CODE_OK = 200,
    SUCCESS_CODE_CREATED = 201,
    SUCCESS_CODE_CREATED_OR_UPDATED = 204,
    FAILED = 400,
    NOT_FOUND = 404,
    UNEXPECTED_ERROR = 500,
}
